"use client";

import { useEffect, useRef, useState } from "react";
import { Bell, CheckCircle2, Download, FileArchive, GitBranch, LoaderCircle, Moon, Settings2, Sun, UploadCloud, Volume2, VolumeX, Zap } from "lucide-react";
import { useTheme } from "next-themes";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { StatusBadge } from "@/components/ui/status";
import { PushSetup } from "@/components/push-setup";
import { ProjectInspector } from "@/components/project-inspector";
import { TerminalBubble } from "@/components/terminal-bubble";

type BuildType = "android" | "flutter" | "java" | "kotlin" | "dart";
type Job = { id: string; runId: number; status: string; url?: string; error?: string };

function playDoneSound() { try { const ctx = new AudioContext(); const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.frequency.value = 740; gain.gain.setValueAtTime(.0001, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.13, ctx.currentTime + .02); gain.gain.exponentialRampToValueAtTime(.0001, ctx.currentTime + .35); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .36); } catch {} }

export default function Home() {
  const { theme, setTheme } = useTheme();
  const [file, setFile] = useState<File | null>(null); const [type, setType] = useState<BuildType>("android"); const [variant, setVariant] = useState("debug"); const [output, setOutput] = useState("apk"); const [sdk, setSdk] = useState("35");
  const [job, setJob] = useState<Job | null>(null); const [busy, setBusy] = useState(false); const [sound, setSound] = useState(true); const [accessKey, setAccessKey] = useState(""); const [message, setMessage] = useState("Ready to build"); const timer = useRef<ReturnType<typeof setInterval> | null>(null);
  useEffect(() => () => { if (timer.current) clearInterval(timer.current); }, []);
  useEffect(() => { if (job?.status === "success") { if (sound) playDoneSound(); if ("Notification" in window && Notification.permission === "granted") new Notification("Build selesai", { body: "Output project siap didownload." }); } }, [job?.status]);
  async function poll(runId: number) { const r = await fetch(`/api/build-status?runId=${runId}`, { cache: "no-store", headers: { "x-build-key": accessKey } }); const d = await r.json(); if (!r.ok) { setMessage(d.error || "Status check failed"); return; } setJob((j) => ({ ...(j || { id: String(runId), runId }), ...d })); setMessage(d.status === "success" ? "Build selesai — output siap didownload" : d.status === "failure" ? "Build gagal — buka log GitHub" : d.status); if (["success", "failure", "cancelled"].includes(d.status)) { if (timer.current) clearInterval(timer.current); timer.current = null; setBusy(false); } }
  async function startBuild() { if (!file) return; setBusy(true); setJob(null); setMessage("Uploading project ZIP..."); try { const form = new FormData(); form.append("file", file); const up = await fetch("/api/upload", { method: "POST", body: form, headers: { "x-build-key": accessKey } }); const u = await up.json(); if (!up.ok) throw new Error(u.error); setMessage("Starting GitHub Actions..."); const r = await fetch("/api/build", { method: "POST", headers: { "Content-Type": "application/json", "x-build-key": accessKey }, body: JSON.stringify({ sourceUrl: u.url, type, variant, output, sdk }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setJob(d); setMessage("queued"); timer.current = setInterval(() => poll(d.runId), 3000); await poll(d.runId); } catch (e) { setMessage(e instanceof Error ? e.message : "Build failed"); setBusy(false); } }
  const isDark = theme === "dark";
  async function downloadOutput() {
    if (!job?.runId) return;
    const response = await fetch(`/api/artifact?runId=${job.runId}`, { headers: { "x-build-key": accessKey } });
    if (!response.ok) { setMessage("Download artifact gagal"); return; }
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = type === "android" || type === "flutter" ? (output === "aab" ? "app-release.aab" : "app-debug.apk") : "build-output"; anchor.click(); URL.revokeObjectURL(url);
  }
  return <main className="mx-auto min-h-screen max-w-6xl px-5 py-6 sm:py-10">
    <nav className="mb-14 flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-2xl bg-foreground text-background"><Zap className="size-5" /></div><div><div className="font-bold tracking-tight">BuildBox</div><div className="text-xs text-muted-foreground">personal compiler</div></div></div><div className="flex items-center gap-2"><PushSetup /><Button variant="outline" size="icon" aria-label="Toggle theme" onClick={() => setTheme(isDark ? "light" : "dark")}>{isDark ? <Sun className="size-4" /> : <Moon className="size-4" />}</Button></div></nav>
    <section className="mb-10 max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-border px-3 py-1 text-xs font-semibold text-muted-foreground"><GitBranch className="size-3.5" /> powered by GitHub Actions</div><h1 className="text-4xl font-black tracking-[-.055em] sm:text-6xl">Compile project.<br /><span className="text-muted-foreground">Download output.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-muted-foreground">Upload project ZIP Android, Jetpack Compose, Flutter, Java, Kotlin, atau Dart. Simple, private, dan langsung jadi artifact.</p></section>
    <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]">
      <section className="card p-5 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-lg font-bold">New build</h2><p className="text-sm text-muted-foreground">Atur build sebelum compile.</p></div><Settings2 className="size-5 text-muted-foreground" /></div><ProjectInspector file={file} onFile={setFile} /><div className="mt-4"><label className="label">Personal build key <span className="font-normal">(optional)</span></label><Input type="password" placeholder="Isi jika BUILD_ACCESS_KEY diaktifkan" value={accessKey} onChange={(e) => setAccessKey(e.target.value)} autoComplete="off" /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Project type"><select className="field" value={type} onChange={(e) => setType(e.target.value as BuildType)}>{["android", "flutter", "java", "kotlin", "dart"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Build variant"><select className="field" value={variant} onChange={(e) => setVariant(e.target.value)}><option>debug</option><option>release</option></select></Field><Field label="Output"><select className="field" value={output} onChange={(e) => setOutput(e.target.value)}><option value="apk">APK</option><option value="aab">AAB</option><option value="jar">JAR</option><option value="zip">ZIP</option></select></Field><Field label="Android SDK"><select className="field" value={sdk} onChange={(e) => setSdk(e.target.value)}><option value="34">API 34</option><option value="35">API 35</option><option value="36">API 36</option></select></Field></div><div className="mt-6 flex items-center justify-between rounded-xl bg-muted px-4 py-3"><div className="flex items-center gap-2 text-sm"><button aria-label="Toggle sound" onClick={() => setSound(!sound)}>{sound ? <Volume2 className="size-4" /> : <VolumeX className="size-4" />}</button>Sound saat selesai</div><Switch checked={sound} onCheckedChange={setSound} aria-label="Build sound" /></div><Button className="mt-5 w-full" disabled={!file || busy} onClick={startBuild}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Zap className="size-4" />}{busy ? "BUILDING..." : "COMPILE PROJECT"}</Button></section>
      <section className="card flex min-h-[390px] flex-col p-5 sm:p-7"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Build status</h2><p className="text-sm text-muted-foreground">Pantau proses compile.</p></div>{job ? <StatusBadge status={job.status} /> : <FileArchive className="size-5 text-muted-foreground" />}</div><div className="mt-6 flex flex-1 flex-col items-center justify-center text-center"><div className={`mb-4 flex size-16 items-center justify-center rounded-3xl ${job?.status === "success" ? "bg-green-500/15 text-green-600" : "bg-muted text-muted-foreground"}`}>{job?.status === "success" ? <CheckCircle2 className="size-8" /> : busy ? <LoaderCircle className="size-8 animate-spin" /> : <FileArchive className="size-8" />}</div><div className="font-semibold">{message}</div><div className="mt-2 text-xs text-muted-foreground">{job?.runId ? `GitHub Actions run #${job.runId}` : "Belum ada build aktif"}</div>{job?.status === "success" && <button className="btn mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-foreground px-5 font-semibold text-background" onClick={downloadOutput}><Download className="size-4" />Download output</button>}{job?.status === "failure" && <a className="btn mt-6 inline-flex h-11 items-center rounded-xl border border-border px-5 font-semibold" href={job.url} target="_blank">Open GitHub logs</a>}</div></section>
    </div>
    <div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span>Dark/light mengikuti pengaturan sistem.</span><Sheet><SheetTrigger asChild><button className="hover:text-foreground">Advanced info</button></SheetTrigger><SheetContent side="bottom"><SheetHeader><SheetTitle>BuildBox settings</SheetTitle><SheetDescription>Build dijalankan di GitHub Actions. ZIP disimpan sementara sebelum worker mengambilnya.</SheetDescription></SheetHeader><div className="mt-6 grid gap-3 text-sm text-muted-foreground"><div className="rounded-xl bg-muted p-4">Debug APK cocok untuk testing. Release APK/AAB membutuhkan signing key jika ingin publish.</div><div className="rounded-xl bg-muted p-4">Push notification memakai permission browser. Web Push penuh dengan VAPID bisa ditambahkan nanti.</div></div></SheetContent></Sheet></div><footer className="mt-10 border-t border-border pt-5 text-center text-xs text-muted-foreground"><div>Made XyStudio · Dev XyKelOmex</div><div className="mt-1 opacity-70">BuildBox personal compiler · UI/UX for fast builds</div></footer><TerminalBubble runId={job?.runId} accessKey={accessKey} />
  </main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="label">{label}</span>{children}</label>; }
