"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, Download, FileDown, LoaderCircle, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function DownloadPage({ params }: { params: Promise<{ runId: string }> }) {
  const [runId, setRunId] = useState(""); const [status, setStatus] = useState("loading"); const [message, setMessage] = useState("Checking build output..."); const [accessKey, setAccessKey] = useState(""); const [downloading, setDownloading] = useState(false);
  useEffect(() => { params.then(({ runId: id }) => { setRunId(id); const key = localStorage.getItem("buildbox-job"); try { setAccessKey(key ? JSON.parse(key).accessKey || "" : ""); } catch {} }); }, [params]);
  useEffect(() => { if (!runId) return; fetch(`/api/build-status?runId=${runId}`, { headers: { "x-build-key": accessKey }, cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setStatus(data.status); setMessage(data.status === "success" ? "Output siap didownload." : data.status === "failure" ? "Build gagal. Buka log untuk detail." : `Build masih ${data.status}.`); }).catch((error) => { setStatus("error"); setMessage(error instanceof Error ? error.message : "Status tidak bisa dibaca."); }); }, [runId, accessKey]);
  async function download() { setDownloading(true); try { const response = await fetch(`/api/artifact?runId=${runId}`, { headers: { "x-build-key": accessKey } }); if (!response.ok) throw new Error(await response.text()); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "build-output"; anchor.click(); URL.revokeObjectURL(url); setMessage("Download dimulai."); } catch (error) { setMessage(error instanceof Error ? error.message : "Download gagal."); } finally { setDownloading(false); } }
  return <main className="mx-auto min-h-screen max-w-xl px-5 py-12 sm:py-20"><Link href="/" className="text-sm text-muted-foreground hover:text-foreground">← Kembali ke compiler</Link><section className="card mt-8 p-6 text-center sm:p-8"><div className={`mx-auto mb-5 flex size-16 items-center justify-center rounded-3xl ${status === "success" ? "bg-green-500/15 text-green-600" : status === "error" || status === "failure" ? "bg-red-500/15 text-red-600" : "bg-muted text-muted-foreground"}`}>{status === "success" ? <CheckCircle2 className="size-8" /> : status === "error" || status === "failure" ? <XCircle className="size-8" /> : <LoaderCircle className="size-8 animate-spin" />}</div><h1 className="text-3xl font-black">Build output</h1><p className="mt-3 text-sm text-muted-foreground">Run #{runId}</p><div className="mt-6 rounded-xl bg-muted p-4 text-sm">{message}</div>{status === "success" && <Button className="mt-6 w-full" onClick={download} disabled={downloading}><FileDown className="size-4" />{downloading ? "Preparing download..." : "Download APK / Output"}</Button>}{status === "failure" && <a className="btn mt-6 inline-flex h-11 items-center gap-2 rounded-xl border border-border px-5 font-semibold" href={`https://github.com/Kallxy1/androidengine/actions/runs/${runId}`} target="_blank"><Download className="size-4" />Open build logs</a>}</section></main>;
}
