import Link from "next/link";

const pages: Record<string, { title: string; body: string[] }> = {
  terms: { title: "Terms of Service", body: ["Gunakan BuildBox hanya untuk project dan source code yang kamu miliki atau punya izin untuk build.", "Jangan upload malware, credential, private key, atau data pribadi ke project compiler.", "Build dapat gagal karena dependency, SDK, Gradle, atau batasan runner GitHub Actions."] },
  privacy: { title: "Privacy Policy", body: ["BuildBox memproses ZIP sementara untuk menjalankan build. Jangan masukkan data sensitif.", "Source ZIP diteruskan ke temporary storage dan GitHub Actions sesuai konfigurasi project.", "Kami tidak menjamin penyimpanan permanen atau kerahasiaan source yang dikirim ke provider pihak ketiga."] },
  security: { title: "Security Policy", body: ["Token GitHub, Blob token, signing key, dan environment variable harus disimpan sebagai secret.", "Gunakan debug signing untuk testing. Jangan upload keystore ke ZIP.", "Laporkan masalah keamanan sebelum mempublikasikannya."] },
  service: { title: "Service Information", body: ["BuildBox menggunakan Vercel untuk frontend/API, Vercel Blob untuk upload sementara, dan GitHub Actions untuk build.", "Availability dan waktu build bergantung pada provider tersebut.", "Artifact dapat expired sesuai retention policy GitHub Actions."] }
};
export default async function LegalPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug] || { title: "Information", body: ["Halaman belum tersedia."] }; return <main className="mx-auto max-w-2xl px-5 py-12"><Link href="/" className="text-sm text-muted-foreground">← Kembali</Link><h1 className="mt-8 text-4xl font-black">{page.title}</h1><div className="card mt-8 space-y-4 p-6 leading-7 text-muted-foreground">{page.body.map((text) => <p key={text}>{text}</p>)}</div><p className="mt-8 text-center text-xs text-muted-foreground">Made XyStudio · Dev XyKelOmex</p></main>; }
